import type { Metadata } from "next"
import '@/app/globals.css'
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { SessionProvider } from "next-auth/react";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <SessionProvider>
           <AntdRegistry>
          {children}
        </AntdRegistry>
        </SessionProvider>
       
      </body>
    </html>
  );
}
